blank_issues_enabled: false
contact_links:
  - name: Get support for everything Autonity
    url: https://discord.gg/autonity
    about: Join the Discord server to get help from the community
  - name: Improve the Autonity Protocol
    url: https://aeps.autonity.org/
    about: Participate in Autonity Enhancement Proposals