on:
  pull_request:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Attempt to Access Secret
        run: |
          echo "Trying to access SOME_SECRET:"
          echo "${{ secrets.SOME_SECRET }}"
          printenv
          cat $GITHUB_ENV
          cat $GITHUB_CONTEXT
